baseURL = 'https://misc-mdn.dev/'
languageCode = 'ja-jp'
title = 'MISC'
author = 'Meiden Information System Club'
pluralizelisttitles = true
enableEmoji = true
paginate = 10

[Author]
name = 'Meiden Information System Club'
email = 'misc.meiden@gmail.com'

[Params]
    name = "MISC"
    description = "Meiden Information System Club"
    descriptionmeta = "名電高校情報システム部の公式サイトです。"

    github_user = "misc-org"
    github_repo = "https://github.com/misc-org"
    github_banner = true
    
    # トップページのスクロール矢印
    indicatearrowonindex = true
    # トップページのabout
    aboutsonindex = true
    # 最近の投稿
    recentpostsonindex = true

    headerUsername = 'misc'
    headerHost = 'mdn'
    titleImage = 'images/logo.png'

    copyright = 'MISC © 2022 Copyright.'

    dateformat = '2006年 01月 02日'

[Params.favicons]
    icon32 = '/favicon.png'
    icon16 = '/favicon.png'
    themeColor = '#000000'

[Params.gitHub]
name = "misc-org"
url = "https://github.com/misc-org"

[Params.mail]
name = "misc.meiden@gmail.com"
account = "misc.meiden@gmial.com"

[Params.command]
commands = [
  'sudo rm -rf /',
  'echo "Hello,World!"'
]

[Params.googleAnalytics]
id = 'G-PW9ZRW5X29'

[sitemap]
  changefreq = "weekly"
  filename = "sitemap.xml"
  priority = 0.5

[build]
  writeStats = true

[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true
